# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'northwind_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'northwind_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  northwind_analytics:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    
    # Config for intermediate models
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
    
    # Config for marts
    marts:
      +materialized: table
      +docs:
        node_color: "green"
      
      # Core business entities
      core:
        +materialized: table
      
      # Analytics and reporting models
      analytics:
        +materialized: view

# Add some useful variables
vars:
  # Set the timezone for date calculations
  timezone: "UTC"
  
  # Set the start date for historical analysis
  start_date: "1996-01-01"

# Configure tests
tests:
  +store_failures: true